### ISSUE TITLE
Plug doesn't read settings?

### ISSUE THREAD

**Issue by h3ndrik** [silverbulletmd/silverbullet-pub#13]
I've copy-pasted the publish part in my SETTINGS file but this plug doesn't seem to read any of them:

```
This page contains some configuration overrides for SilverBullet. [...]

\`\`\`space-config
indexPage: index
libraries:
- import: "[[!silverbullet.md/Library/Core/*]]"

publish:
  indexPage: test
  title: "h3ndriks notes"
  template: "template/page"
  destPrefix: "_public/"
  removeHashtags: true
  removeUnpublishedLinks: false
  publishAll: true
  tags:
  - pub
\`\`\`
```

No matter what I change or configure, the pub plug seems to stick to its default settings.

SilverBullet version 0.9.2
